### ISSUE TITLE
когда вы выложите?

### ISSUE THREAD

**Issue by MrDoni98** [SergeyDertan/PrivateRegionProtector#1]
Мой друг купил ваш плагин у когото но после перезагрузки сервера , все прижаты удаляются , считай деньги на ветер :( буду вам ужасно благодарен :) если вы его закончить сдесь

**Comment by SergeyDertan** [comment]
Кто?Скорее всего не я продал

**Comment by MrDoni98** [comment]
Я не знаю но точно не вы )) 
Можете дать мне плагин а то мне даже сегодня его за 1500 предлагали купить
У меня больше 100 нету :((

**Comment by MrDoni98** [comment]
А всё извените я код не посмотрел , вы уже выложили , спасибо огромное

**Comment by MrDoni98** [comment]
Почему после перезагрузки приват удаляется?

**Comment by SergeyDertan** [comment]
Уже нет.

**Comment by MrDoni98** [comment]
когда я собераю phar файл из архива(через сайт)
мне пишет
Inspections

Classpath
Inspection result: Passed
Info
Main class scanned: Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorMain
Main class file found at src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorMain.php
Bad practice
Inspection result: Warning
Warnings
PluginBase::$config is already defined in PocketMine PluginBase class. Strange errors will occur if you override $this->config yourself. For example, when you decide to use $this->saveDefaultConfig() later, it will not work.
You are recommended to improve this by renaming $this->config to something else, or to use $this->saveDefaultConfig() and related functions.
End of inspections

это нормально?
